experiment:
  model_name: cartnet
  explain_material_ids: []

data:
  data_dir: data/processed
  target: [formation_energy_per_atom]
  batch_size: 32
  num_workers: 0
  train_ratio: 0.8
  val_ratio: 0.1
  seed: 42

model:
  dim_in: 118
  dim_rbf: 16
  num_layers: 5
  radius: 5.0
  invariant: false
  temperature: false
  atom_types: false
  cholesky: false
  jk_mode: last
  layer_type: transformer
  dim_hidden: 128
  use_residual: true
  num_heads: 4


training:
  device: cuda
  epochs: 500
  lr: 0.001

  optimizer:
    name: adam
    weight_decay: 0.0001

  scheduler:
    name: onecycle
    max_lr: 0.001
    pct_start: 0.1
