experiment:
  model_name: cartnet
  explain_material_ids: []

data:
  data_dir: data/processed
  target: [formation_energy_per_atom]
  batch_size: 64
  num_workers: 0
  train_ratio: 0.8
  val_ratio: 0.1
  onehot: false
  jitter_std: [0.0, 0.01, 0.03]
  seed: 42

model:
  dim_in: 118
  dim_rbf: 16
  num_layers: [3, 5, 7]
  radius: [5.0, 8.0, 16.0]
  invariant: false
  temperature: false
  atom_types: true
  cholesky: false
  jk_mode: last
  layer_type: default
  dim_hidden: 128
  use_residual: true
  num_heads: 4


training:
  device: cuda
  epochs: 1000
  lr: 0.001

  optimizer:
    name: adamw
    weight_decay: 0.01

  scheduler:
    name: onecycle
    max_lr: 0.003
    pct_start: 0.1
