experiment:
  model_name: cgcnn
  explain_material_ids: []

data:
  data_dir: data/processed
  target: [formation_energy_per_atom]
  batch_size: 64
  num_workers: 0
  train_ratio: 0.8
  val_ratio: 0.1
  seed: 42

model:
  node_input_dim: 118
  edge_input_dim: 1
  hidden_dim: [16, 32, 64]
  num_layers: [3, 5, 7, 10]
  output_dim: 1
  pooling: mean

training:
  device: cuda
  epochs: 1500
  lr: 0.001

  optimizer:
    name: adam
    weight_decay: 0.0001

  scheduler:
    - name: onecycle
      max_lr: 0.005
      pct_start: [0.1, 0.2]
    - name: step
      step_size: 0
      gamma: 0.9
