experiment:
  model_name: cgcnn
  save_dir: checkpoints

data:
  data_dir: data/processed
  target: formation_energy_per_atom
  batch_size: 32
  num_workers: 0
  train_ratio: 0.8
  val_ratio: 0.1
  seed: 42

model:
  hidden_dim: 64
  num_layers: 3
  node_input_dim: 20
  edge_input_dim: 1
  output_dim: 1

training:
  epochs: 30
  lr: 0.001
  device: cuda
