experiment:
  model_name: unicrystal
  explain_material_ids: []

data:
  data_dir: data/processed
  target: [formation_energy_per_atom]
  batch_size: 64
  num_workers: 0
  train_ratio: 0.8
  val_ratio: 0.1
  onehot: false
  jitter_std: 0.01
  seed: 42

model:
  conv_layers: 5
  edge_features: 128
  hidden_dim: 128
  fc_features: 128
  output_features: 1
  num_heads: 4
  mix_layers: [True, False]
  mixer_type: [residual_gate, cross_attention, moe_soft_routing]
  dropout: [0.1, 0.2]
  radius: 16.0


training:
  device: cuda
  epochs: 1500
  lr: 0.001

  optimizer:
    name: adamw
    weight_decay: 0.01

  scheduler:
    name: onecycle
    max_lr: 0.005
    pct_start: 0.1
