experiment:
  model_name: unicrystal
  explain_material_ids: []

data:
  data_dir: data
  dataset: mp
  target: [formation_energy_per_atom]
  batch_size: 128
  num_workers: 1
  radius: 8.0
  seed: 42
  max_neighbors: 30
  is_norm: false
  persistent_workers: true

model:
  num_cart_layers: 3
  num_mat_layers: 4
  edge_features: 128
  hidden_dim: 128
  fc_features: 128
  output_features: 1
  num_heads: 4
  dropout: 0.05
  radius: 8.0
  use_att_fusion: true


training:
  device: cuda
  epochs: 1500
  lr: 0.001
  loss_fn:
    type: l1

  optimizer:
    name: adamw
    weight_decay: 0.01

  scheduler:
    name: onecycle
    max_lr: 0.004
    pct_start: 0.1
